<a href="https://colab.research.google.com/github/berkayberatsonmez/Machine-Learning-Course/blob/main/Anomaly_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [258]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 500)
pd.set_option('display.max_rows', None)

In [259]:
import os
import glob
files = os.path.join('/content/','random*.pcap_Flow.csv')
files = glob.glob(files)
ddos = pd.read_csv('/content/Ddos.csv')
df = pd.concat(map(pd.read_csv, files), ignore_index=True)

In [260]:
ddos = ddos.loc[:,[' Fwd Packet Length Std',' Packet Length Std',' Flow IAT Min',' Min Packet Length',' Average Packet Size',' Fwd Packet Length Min',' Fwd Packet Length Max',' Max Packet Length',' Label']]
df = df.loc[:,['Fwd Packet Length Std','Packet Length Std','Flow IAT Min','Packet Length Min','Average Packet Size','Fwd Packet Length Min','Fwd Packet Length Max','Packet Length Max','Label']]

In [261]:
ddos.columns ='Fwd Packet Length Std','Packet Length Std','Flow IAT Min','Packet Length Min','Average Packet Size','Fwd Packet Length Min','Fwd Packet Length Max','Packet Length Max','Label'

In [262]:
df = df.append(ddos)

In [263]:
df['Label'] = [ 1 if each == "BENIGN" else 0 for each in df['Label']]

In [264]:
df = df.sample(frac=1, random_state=1)

In [265]:
y = df['Label'].values
x_data= df.drop(["Label"],axis=1)

In [266]:
x = x_data

In [267]:
from sklearn.model_selection import train_test_split
x_train, x_test,y_train, y_test = train_test_split(x,y,test_size = 0.4,random_state = 42)

In [268]:
from sklearn.svm import SVC
classifier = SVC(kernel='rbf', random_state = 0)
classifier.fit(x_train, y_train)

SVC(random_state=0)

In [269]:
y_pred = classifier.predict(x_test)


In [270]:
from sklearn.metrics import confusion_matrix
print('SVC')
cm = confusion_matrix(y_test, y_pred)
print(cm)

SVC
[[453   0]
 [ 58   0]]


In [271]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
# Fit
reg.fit(x_train,y_train)
# R^2 
print('R^2 score: ',reg.score(x, y))

R^2 score:  0.4371681010345615


In [272]:
print('REG')
cm = confusion_matrix(y_test,y_pred)
print(cm)

REG
[[453   0]
 [ 58   0]]


In [273]:
from sklearn.model_selection import cross_val_score
reg = LinearRegression()
k = 5
cv_result = cross_val_score(reg,x,y,cv=k) # uses R^2 as score 
print('CV Scores: ',cv_result)
print('CV scores average: ',np.sum(cv_result)/k)

CV Scores:  [0.37522618 0.28995281 0.49897333 0.46641131 0.47019294]
CV scores average:  0.42015131246272813


In [274]:
from sklearn.linear_model import LogisticRegression

logr = LogisticRegression(random_state = 0) 
logr.fit(x_train,y_train)

y_pred = logr.predict(x_test)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


In [275]:
print('LOGR')
cm = confusion_matrix(y_test,y_pred)
print(cm)

LOGR
[[445   8]
 [ 13  45]]


In [276]:
#KNN
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors = 1, metric = 'minkowski')

knn.fit(x_train,y_train)

y_pred = knn.predict(x_test)

In [277]:
print('KNN')
cm = confusion_matrix(y_test,y_pred)
print(cm)

KNN
[[452   1]
 [  6  52]]


In [278]:
#support vector machine
from sklearn.svm import SVC
#svc = SVC(kernel = 'linear') #doğrusal formülünü kullanıyoruz
svc = SVC(kernel = 'rbf') #başarı oranına bakmak için değişik kernelları deniyoruz 
#svc = SVC(kernel = 'poly')
svc.fit(x_train,y_train)

y_pred = svc.predict(x_test)

In [279]:
print('SVC')
cm = confusion_matrix(y_test,y_pred)
print(cm)

SVC
[[453   0]
 [ 58   0]]


In [280]:
test = pd.read_csv('rftest.csv')

In [281]:
test = test.loc[:,[' Fwd Packet Length Std',' Packet Length Std',' Flow IAT Min',' Min Packet Length',' Average Packet Size',' Fwd Packet Length Min',' Fwd Packet Length Max',' Max Packet Length',' Label']]

In [282]:
test.columns ='Fwd Packet Length Std','Packet Length Std','Flow IAT Min','Packet Length Min','Average Packet Size','Fwd Packet Length Min','Fwd Packet Length Max','Packet Length Max','Label'

In [283]:
test['Label'] = [ 1 if each == "BENIGN" else 0 for each in test['Label']]

In [284]:
x_testt= test.drop(["Label"],axis=1)
ytest = test['Label'].values

In [285]:
y_test_pred= knn.predict(x_testt)

In [286]:
cm = confusion_matrix(ytest,y_test_pred)
cm

array([[ 873,   23],
       [ 938, 3257]])

In [287]:
from sklearn.metrics import classification_report
print('Classification report: \n',classification_report(ytest,y_test_pred))

Classification report: 
               precision    recall  f1-score   support

           0       0.48      0.97      0.64       896
           1       0.99      0.78      0.87      4195

    accuracy                           0.81      5091
   macro avg       0.74      0.88      0.76      5091
weighted avg       0.90      0.81      0.83      5091

